export const SITE_URL = 'https://tryquickdraw.com'
export const APP_URL = 'https://app.tryquickdraw.com'
export const GITHUB_URL = 'https://github.com/quickdrawjs/quickdraw'
export const SITE_NAME = 'Quickdraw'
export const SITE_TAGLINE = 'The MIT-licensed infinite-canvas whiteboard SDK'
